# Credenciales para Earth Engine
EARTHENGINE_TOKEN = "ee-mawucano25"

# Configuración de la aplicación
[general]
TITLE = "Analizador Forrajero GEE"
DESCRIPTION = "Análisis de productividad forrajera con Sentinel-2"

# Límites de la aplicación
MAX_FILE_SIZE_MB = 50
MAX_POLYGONS = 100
